web:
  build: ./web
  ports:
    - "8000:8000"
  environment:
    VBO_URI_TEMPLATE: "https://api-acc.datapunt.amsterdam.nl/bag/verblijfsobject/{landelijk_id}/"
    UWSGI_HTTP: ":8000"
    UWSGI_MODULE: "zwaailicht.wsgi:application"
    UWSGI_MASTER: 1
    UWSGI_STATIC_MAP: "/static=/static"
    UWSGI_PROCESSES: 4
